// Wild card searches. Subjects from every corner of life, so a search lands
// somewhere the viewer has never been. Astronaut.io does the same with
// camera file names to find unwatched home videos.

export const WILD_WORDS = `
blacksmith, glacier, submarine, beekeeping, origami, volcano, lighthouse keeper, taxidermy, tunnel boring machine, orchestra,
bonsai, shipwreck, falconry, pottery wheel, avalanche, monastery, locksmith, tornado chasing, circus, railway,
sawmill, lava flow, mushroom foraging, telescope, desert crossing, ferry, quarry, knot tying, windmill, sculpture,
puppet, harbor, lumberjack, typewriter, clockmaker, parrot, octopus, rodeo, marathon, cathedral,
bunker, blizzard, coral reef, caravan, glassblowing, woodturning, stonemason, bookbinding, calligraphy, perfume making,
chess, sumo, tractor, salvage diving, icebreaker ship, zeppelin, hovercraft, ghost town, abandoned mall, car restoration,
engine rebuild, primitive technology, bushcraft, homestead, off grid living, sailing storm, deep sea fishing, crab boat, sheep shearing, cattle drive,
forge, watch repair, piano tuning, violin making, archery, sword making, armor making, fencing, kendo, wrestling,
skydiving, free solo climbing, cave diving, ice fishing, dog sled, reindeer herding, nomad life, street food, night market, bazaar,
train journey, cargo ship, truck driver, crane operator, demolition, welding, roofing, tiny house, log cabin build, treehouse,
magic trick, ventriloquist, speedrun, world record, domino, rube goldberg, marble run, meteorite, fossil hunting, archaeology dig,
mummy, pyramid, shipbuilding, canoe, whitewater, kayak, beatboxing, drum corps, opera, lego technic,
model railway, aquarium, terrarium, snake catcher, storm chaser, oil rig, nuclear plant, dam, skyscraper, space station,
rocket launch, airport, air traffic control, aircraft carrier, tank restoration, medieval village, castle, samurai, viking, roman legion,
gladiator, knight, pirate, cowboy, gold rush, oregon trail, lewis and clark, polar expedition, antarctica, arctic,
sahara, amazon rainforest, himalaya, mount everest, k2, sherpa, mongolia, siberia, greenland, iceland,
faroe islands, svalbard, patagonia, atacama, okavango, serengeti, madagascar, borneo, papua new guinea, tasmania,
outback, bhutan, nepal, tibet, kyrgyzstan, tajikistan, pamir highway, silk road, caspian sea, aral sea,
chernobyl, fukushima, pompeii, petra, angkor wat, machu picchu, easter island, stonehenge, gobekli tepe, catalhoyuk,
babylon, sumer, assyria, hittites, minoans, mycenae, sparta, carthage, phoenicians, etruscans,
byzantium, ottoman empire, mughal empire, khmer empire, aztec, maya, inca, olmec, mali empire, great zimbabwe,
songhai, benin bronzes, aksum, nubia, kush, scythians, huns, mongol empire, genghis khan, tamerlane,
crusades, hundred years war, thirty years war, napoleonic wars, american civil war, trench warfare, enigma machine, codebreakers, d day, battle of stalingrad,
cold war, berlin wall, cuban missile crisis, space race, apollo program, voyager probe, hubble, james webb telescope, mars rover, international space station,
black hole, neutron star, supernova, exoplanet, dark matter, quantum physics, particle accelerator, cern, fusion reactor, superconductor,
semiconductor fab, microchip, transistor, vacuum tube, analog computer, mainframe, punch card, early internet, bulletin board system, demoscene,
pinball machine, arcade cabinet, jukebox, vinyl pressing, cassette tape, reel to reel, tube amplifier, synthesizer, theremin, modular synth,
pipe organ, bagpipes, didgeridoo, throat singing, flamenco, tango, sea shanty, yodeling, gospel choir, brass band,
steel drum, gamelan, sitar, koto, taiko drumming, mariachi, polka, bluegrass, delta blues, jazz club,
barbershop quartet, a cappella, marching band, bell ringing, carillon, glass harmonica, hurdy gurdy, banjo making, guitar building, drum making,
woodcarving, chainsaw carving, ice sculpture, sand sculpture, sandcastle, stained glass, mosaic, fresco, tapestry, weaving,
spinning wool, dyeing fabric, indigo dye, quilting, embroidery, lace making, knitting, crochet, tailoring, shoemaking,
leatherwork, saddle making, hat making, wig making, jewelry making, gem cutting, goldsmith, silversmith, coppersmith, tinsmith,
pewter casting, bronze casting, bell foundry, iron smelting, bloomery, charcoal making, lime kiln, brick making, adobe, rammed earth,
thatched roof, timber framing, dry stone wall, cob house, yurt, igloo, tipi, longhouse, stilt house, cave dwelling,
underground city, catacombs, sewer system, aqueduct, canal lock, ship lift, swing bridge, suspension bridge, covered bridge, rope bridge,
tunnel collapse, mine rescue, coal mine, salt mine, gold mine, diamond mine, opal mining, amber, jade carving, pearl diving,
sponge diving, free diving, spearfishing, lobster fishing, oyster farming, seaweed farming, salmon run, tuna auction, fish market, whaling history,
shark tagging, whale watching, manatee, sea otter, walrus, narwhal, orca, giant squid, anglerfish, deep sea creatures,
hydrothermal vent, tide pool, mangrove, kelp forest, sea turtle, jellyfish, nudibranch, mantis shrimp, horseshoe crab, coconut crab,
army ants, leafcutter ants, termite mound, honeyguide bird, bowerbird, lyrebird, bird of paradise, hummingbird, owl rescue, vulture,
condor, albatross, penguin colony, puffin, flamingo, peacock, crow intelligence, raven, magpie, pigeon racing,
homing pigeon, chicken keeping, duck farm, goose, turkey farm, quail, ostrich farm, emu, cassowary, kiwi bird,
platypus, echidna, wombat, kangaroo, koala rescue, tasmanian devil, sloth, armadillo, anteater, capybara,
tapir, okapi, giraffe, rhino, elephant orphanage, hippo, crocodile farm, alligator, komodo dragon, chameleon,
gecko, iguana, tortoise, axolotl, salamander, poison dart frog, cane toad, python hunting, rattlesnake roundup, venom milking,
scorpion, tarantula, spider silk, praying mantis, stick insect, monarch butterfly, moth, firefly, cicada, locust swarm,
beetle collecting, dung beetle, silkworm, cricket farming, edible insects, honey hunting, mead making, wine making, cider pressing, beer brewing,
sake brewing, whisky distillery, rum, tequila, absinthe, coffee roasting, tea plantation, matcha, cacao farming, chocolate making,
cheese making, cheese cave, sourdough, bagel, pretzel, croissant, pasta making, ramen shop, sushi chef, knife sharpening,
knife making, cast iron restoration, wok hei, barbecue pit, smokehouse, charcuterie, sausage making, butcher, bakery at night, pie contest,
chili cookoff, hot sauce, pickling, fermentation, kimchi, miso, tofu making, noodle pulling, dumpling, tamale,
tortilla, empanada, paella, curry, tandoor, kebab, shawarma, falafel, baklava, gelato,
ice cream factory, candy factory, cotton candy, rock candy, lollipop, chewing gum, popcorn, potato chip factory, cereal factory, bottling plant,
factory tour, assembly line, car factory, steel mill, paper mill, glass factory, pencil factory, crayon factory, toy factory, shoe factory,
textile mill, cotton gin, flour mill, water wheel, steam engine, traction engine, steam locomotive, narrow gauge railway, funicular, cable car,
gondola lift, monorail, maglev, subway construction, tunnel boring, bridge demolition, building implosion, skyscraper window cleaning, elevator repair, escalator,
clock tower, big ben, astronomical clock, sundial, hourglass, mechanical calculator, slide rule, abacus, cipher, secret language,
sign language, morse code, ham radio, shortwave, numbers station, telegraph, switchboard operator, rotary phone, pay phone, pneumatic tube,
postal service, mail train, airship, hot air balloon, glider, ultralight, seaplane, bush pilot, crop duster, aerobatics,
air show, fighter jet, bomber, helicopter rescue, coast guard, lifeboat, lighthouse, buoy tender, tugboat, barge,
riverboat, paddle steamer, houseboat, canal boat, gondolier, dhow, junk ship, tall ship, clipper ship, galleon,
trireme, longship, raft voyage, kon tiki, ocean rowing, solo sailing, round the world, shipping container, port of rotterdam, panama canal,
suez canal, ever given, ship breaking, scrapyard, junkyard, auto salvage, barn find, rust bucket, hot rod, lowrider,
monster truck, demolition derby, figure eight racing, drag racing, rally racing, hill climb, ice racing, soapbox derby, lawn mower racing, go kart,
motorcycle restoration, sidecar racing, isle of man tt, enduro, trials bike, unicycle, penny farthing, tandem bicycle, cargo bike, bike messenger,
rickshaw, tuk tuk, jeepney, chicken bus, matatu, camel caravan, horse drawn carriage, wagon wheel, wheelwright, cooper barrel making,
basket weaving, broom making, candle making, soap making, paper making, ink making, pen making, quill, letterpress, printing press,
typesetting, bookshop, library, archive, manuscript restoration, painting restoration, art forgery, art heist, museum storage, museum night,
wax museum, curiosity cabinet, oddities, antique shop, flea market, auction house, estate sale, pawn shop, thrift flip, garage sale,
lost and found, treasure hunt, metal detecting, mudlarking, beachcombing, sea glass, geocaching, urban exploration, lost city, sunken city,
atlantis, el dorado, shangri la, bermuda triangle, roanoke, oak island, nazca lines, voynich manuscript, antikythera mechanism, baghdad battery,
dyatlov pass, tunguska event, mary celeste, flight 19, franklin expedition, donner party, shackleton, scott expedition, amundsen, nansen,
hillary and tenzing, marco polo, ibn battuta, zheng he, magellan, captain cook, darwin voyage, humboldt, livingstone, burton,
pony express, stagecoach, wild west town, saloon, sheriff, outlaw, train robbery, bank robbery, prison escape, alcatraz,
devil's island, penal colony, shipwreck survivor, castaway, desert island, survival at sea, plane crash survival, jungle survival, arctic survival, mountain rescue,
search and rescue dog, bloodhound, sheepdog trial, police dog, guide dog, sled dog race, iditarod, greyhound, dog show, cat show,
horse whisperer, wild horses, mustang, donkey sanctuary, mule, llama, alpaca, yak, water buffalo, camel milk,
goat herding, cheese goats, shepherd, transhumance, alpine pasture, cowbell, swiss village, dutch windmills, tulip fields, flower market,
rose farm, lavender field, saffron harvest, vanilla farm, pepper plantation, cinnamon, nutmeg, spice market, tea ceremony, kimono,
geisha, kabuki, noh theatre, bunraku puppet, shadow puppets, wayang, peking opera, lion dance, dragon boat, lantern festival,
holi festival, diwali, day of the dead, carnival, mardi gras, oktoberfest, la tomatina, running of the bulls, cheese rolling, bog snorkelling,
wife carrying, toe wrestling, worm charming, egg throwing, pumpkin regatta, giant pumpkin, giant vegetable, county fair, state fair, livestock show,
4h, barn raising, amish, mennonite, shaker furniture, hutterite, monk life, nun, hermit, desert monastery,
mount athos, buddhist temple, shaolin, zen garden, rock garden, japanese garden, bonsai nursery, topiary, hedge maze, corn maze,
botanical garden, greenhouse, orchid hunter, carnivorous plants, venus flytrap, giant redwood, baobab, banyan tree, dragon blood tree, bristlecone pine,
petrified forest, slot canyon, sinkhole, cenote, karst, limestone cave, ice cave, lava tube, salt flat, sand dunes,
singing dunes, quicksand, mud volcano, geyser, hot spring, sulfur mine, acid lake, crater lake, meteor crater, impact crater,
northern lights, ball lightning, waterspout, dust devil, haboob, monsoon, typhoon, hurricane hunter, weather balloon, weather station,
lighthouse storm, rogue wave, tsunami, earthquake engineering, seismograph, volcano observatory, lava lake, pyroclastic flow, ash cloud, volcanic winter,
ice age, mammoth, saber tooth, cave bear, neanderthal, cave painting, lascaux, rock art, petroglyph, stone tools,
flint knapping, atlatl, bow drill fire, friction fire, primitive pottery, birch bark canoe, dugout canoe, bark house, wattle and daub, iron age village,
experimental archaeology, living history, reenactment, jousting, longbow, crossbow, trebuchet, catapult, siege tower, castle siege,
moat, drawbridge, portcullis, dungeon, armory, chainmail, plate armor, helmet making, shield wall, medieval cooking,
medieval medicine, plague doctor, apothecary, herbalist, alchemy, astrology history, tarot history, witch trials, folklore, fairy tale origins,
mythology, norse mythology, greek mythology, egyptian gods, japanese yokai, slavic folklore, celtic legend, arthurian legend, robin hood, beowulf,
epic of gilgamesh, odyssey, iliad, dante, shakespeare, globe theatre, puppet theatre, mime, clown school, juggling,
plate spinning, sword swallowing, fire breathing, knife throwing, trapeze, tightrope, high wire, stilt walking, contortion, strongman,
arm wrestling, tug of war, caber toss, highland games, hurling, gaelic football, australian rules, rugby, cricket, lacrosse,
hockey goalie, curling, bobsled, luge, skeleton, ski jumping, biathlon, cross country skiing, snowshoe, ice climbing,
mountaineering, via ferrata, canyoning, caving, bouldering, slacklining, highlining, base jumping, wingsuit, paragliding,
hang gliding, kitesurfing, windsurfing, big wave surfing, bodyboarding, stand up paddle, rowing crew, dragon boat racing, canoe polo, water polo,
synchronized swimming, high diving, cliff diving, open water swimming, channel swim, ice swimming, triathlon, ultramarathon, trail running, fell running,
orienteering, adventure race, obstacle course, parkour, freerunning, skateboarding, bmx, mountain biking, downhill, cyclocross,
track cycling, velodrome, tour de france, motocross, speedway, nascar, formula one pit stop, le mans, rally dakar, land speed record,
salt flat racing, bonneville, jet car, rocket car, solar car, electric car conversion, battery factory, wind turbine, solar farm, hydroelectric,
geothermal plant, tidal power, power grid, substation, lineman, transmission tower, pylon, cable laying ship, undersea cable, satellite dish,
radio telescope, observatory, planetarium, meteor shower, eclipse chasing, comet, asteroid mining, space suit, astronaut training, zero gravity,
moon landing, lunar rover, mars colony, space elevator, rocket engine, jet engine, turbine, gearbox, transmission rebuild, diesel engine,
ship engine, locomotive engine, aircraft engine, radial engine, rotary engine, two stroke, chainsaw repair, small engine repair, lawn mower repair, tractor restoration,
combine harvester, grain elevator, silo, hay baling, threshing, plowing match, horse plowing, ox team, draft horse, farrier,
horseshoe, saddle, cowboy boots, spurs, lasso, bull riding, barrel racing, cutting horse, dressage, show jumping,
polo, buzkashi, camel racing, yak racing, elephant polo, ostrich racing, pig racing, snail racing, frog jumping, cockroach racing,
`
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);
